package com.exa.android.reflekt.ui.theme

import androidx.compose.ui.graphics.Color

fun donutDarkColorTokens(
    // M3 semantic
    primary: Color = Primary,
    onPrimary: Color = Color.White,
    primaryContainer: Color = PrimaryDark,
    background: Color = BackgroundDark,
    onBackground: Color = OnBackgroundDark,
    surface: Color = SurfaceDark,
    onSurface: Color = OnBackgroundDark,
    surfaceVariant: Color = InputBackgroundDark,
    onSurfaceVariant: Color = TextSecondaryDark,
    outline: Color = InputBorderDark,
    outlineVariant: Color = DividerDark,
    error: Color = ErrorRed,
    onError: Color = Color.White,
    errorContainer: Color = Color(0xFF93000A),
    onErrorContainer: Color = Color(0xFFFFDAD6),
    // Custom
    cardBackground: Color = CardBackgroundDark,
    cardBorder: Color = CardBorderDark,
    cardText: Color = Color.White,
    illustrationBackground: Color = IllustrationBgDark,
    badgeBorder: Color = DeepDark,
    avatarBorder: Color = Color.White.copy(alpha = 0.2f),
    paginationDotInactive: Color = CardBorderDark,
    barChartLow: Color = Slate600,
    barChartMid: Color = Slate500,
    barChartHigh: Color = Slate400,
    barChartLabel: Color = Slate400,
    formCardBackground: Color = SurfaceDark,
    accentBlue: Color = AccentBlue,
    accentIndigo: Color = AccentIndigo,
    accentGreen: Color = AccentGreen,
    accentPurple: Color = AccentPurple,
    accentYellow: Color = AccentYellow,
    accentOrange: Color = AccentOrange,
    purpleGlow: Color = PurpleGlow,
    googleBlue: Color = GoogleBlue,
    iconOnAccent: Color = Color.White,
): DonutColorTokens = DonutColorTokens(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    cardBackground = cardBackground,
    cardBorder = cardBorder,
    cardText = cardText,
    illustrationBackground = illustrationBackground,
    badgeBorder = badgeBorder,
    avatarBorder = avatarBorder,
    paginationDotInactive = paginationDotInactive,
    barChartLow = barChartLow,
    barChartMid = barChartMid,
    barChartHigh = barChartHigh,
    barChartLabel = barChartLabel,
    formCardBackground = formCardBackground,
    accentBlue = accentBlue,
    accentIndigo = accentIndigo,
    accentGreen = accentGreen,
    accentPurple = accentPurple,
    accentYellow = accentYellow,
    accentOrange = accentOrange,
    purpleGlow = purpleGlow,
    googleBlue = googleBlue,
    iconOnAccent = iconOnAccent,
)