package com.exa.android.reflekt.ui.theme

import androidx.compose.ui.graphics.Color

fun donutLightColorTokens(
    // M3 semantic
    primary: Color = Primary,
    onPrimary: Color = Color.White,
    primaryContainer: Color = PrimaryLight,
    background: Color = BackgroundLight,
    onBackground: Color = OnBackgroundLight,
    surface: Color = SurfaceLight,
    onSurface: Color = OnBackgroundLight,
    surfaceVariant: Color = InputBackgroundLight,
    onSurfaceVariant: Color = TextSecondaryLight,
    outline: Color = InputBorderLight,
    outlineVariant: Color = DividerLight,
    error: Color = ErrorRed,
    onError: Color = Color.White,
    errorContainer: Color = Color(0xFFFFDAD6),
    onErrorContainer: Color = Color(0xFF410002),
    // Custom
    cardBackground: Color = CardBackgroundLight,
    cardBorder: Color = CardBorderLight,
    cardText: Color = OnBackgroundLight,
    illustrationBackground: Color = IllustrationBgLight,
    badgeBorder: Color = Color.White,
    avatarBorder: Color = Color.Black.copy(alpha = 0.1f),
    paginationDotInactive: Color = CardBorderLight,
    barChartLow: Color = CardBorderLight,
    barChartMid: Color = TextSecondaryLight,
    barChartHigh: Color = OnBackgroundLight,
    barChartLabel: Color = TextSecondaryLight,
    formCardBackground: Color = SurfaceLight,
    accentBlue: Color = AccentBlue,
    accentIndigo: Color = AccentIndigo,
    accentGreen: Color = AccentGreen,
    accentPurple: Color = AccentPurple,
    accentYellow: Color = AccentYellow,
    accentOrange: Color = AccentOrange,
    purpleGlow: Color = PurpleGlow,
    googleBlue: Color = GoogleBlue,
    iconOnAccent: Color = Color.White,
): DonutColorTokens = DonutColorTokens(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    cardBackground = cardBackground,
    cardBorder = cardBorder,
    cardText = cardText,
    illustrationBackground = illustrationBackground,
    badgeBorder = badgeBorder,
    avatarBorder = avatarBorder,
    paginationDotInactive = paginationDotInactive,
    barChartLow = barChartLow,
    barChartMid = barChartMid,
    barChartHigh = barChartHigh,
    barChartLabel = barChartLabel,
    formCardBackground = formCardBackground,
    accentBlue = accentBlue,
    accentIndigo = accentIndigo,
    accentGreen = accentGreen,
    accentPurple = accentPurple,
    accentYellow = accentYellow,
    accentOrange = accentOrange,
    purpleGlow = purpleGlow,
    googleBlue = googleBlue,
    iconOnAccent = iconOnAccent,
)